<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\BHoMReferences.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>PythonSchemaGeneration</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BHoM_Engine">
      <HintPath>$(BHoMAssemblies)\BHoM_Engine.dll</HintPath>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="JsonSchema_oM">
      <HintPath>$(BHoMAssemblies)\JsonSchema_oM.dll</HintPath>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
    <Reference Include="JsonSchema_Engine">
      <HintPath>$(BHoMAssemblies)\JsonSchema_Engine.dll</HintPath>
      <SpecificVersion>false</SpecificVersion>
    </Reference>
  </ItemGroup>

</Project>
